import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import localFont from 'next/font/local'
import ThemeProvider from "@/app/context/Theme";
import ThemeWarper from "@/components/ThemeWarper";

const yekanbakh = localFont({
  src: [
    {
      path: '../public/assets/yekanbakhfanum-black.ttf',
      weight: '700',
      style: 'normal',
  },
    {
      path: '../public/assets/yekanbakhfanum-regular.ttf',
      weight: '400',
      style: 'normal',
  },
    {
      path: '../public/assets/yekanbakhfanum-semibold.ttf',
      weight: '200',
      style: 'normal',
  },
  ],
  display: 'swap',
  variable:"--main-black"
})
 

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={`${inter.className} ${yekanbakh.variable} `}>
        <ThemeProvider>
          <ThemeWarper>

        <Navbar/>
        {children}
          </ThemeWarper>
        </ThemeProvider>
        </body>
    </html>
  );
}
